-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "gruvbox"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute", { link = "PreProc" })
hi(0, "@character.special", { link = "Special" })
hi(0, "@comment.error", { link = "Error" })
hi(0, "@comment.info", { link = "SpecialComment" })
hi(0, "@comment.todo", { link = "Todo" })
hi(0, "@comment.warning", { link = "WarningMsg" })
hi(0, "@conditional", { link = "Conditional" })
hi(0, "@conditional.ternary", { link = "Operator" })
hi(0, "@constant.macro", { link = "Macro" })
hi(0, "@constructor", { link = "Function" })
hi(0, "@debug", { link = "Debug" })
hi(0, "@define", { link = "Define" })
hi(0, "@error", { link = "Error" })
hi(0, "@exception", { link = "Exception" })
hi(0, "@field", { link = "Field" })
hi(0, "@float", { link = "Float" })
hi(0, "@function.macro", { link = "Macro" })
hi(0, "@function.method", { link = "Function" })
hi(0, "@function.method.call", { link = "Function" })
hi(0, "@include", { link = "Include" })
hi(0, "@keyword.conditional", { link = "Conditional" })
hi(0, "@keyword.conditional.ternary", { link = "Operator" })
hi(0, "@keyword.debug", { link = "Debug" })
hi(0, "@keyword.directive", { link = "PreProc" })
hi(0, "@keyword.directive.define", { link = "Define" })
hi(0, "@keyword.exception", { link = "Exception" })
hi(0, "@keyword.import", { link = "Include" })
hi(0, "@keyword.repeat", { link = "Repeat" })
hi(0, "@keyword.storage", { link = "StorageClass" })
hi(0, "@label.json", { link = "Field" })
hi(0, "@lsp.type.member", { link = "Function" })
hi(0, "@lsp.type.property", { link = "Field" })
hi(0, "@lsp.typemod.variable.defaultLibrary", { link = "@variable.builtin" })
hi(0, "@markup.heading", { link = "Title" })
hi(0, "@markup.link", { link = "Identifier" })
hi(0, "@markup.link.url", { link = "Link" })
hi(0, "@markup.raw", { link = "String" })
hi(0, "@markup.strikethrough", {})
hi(0, "@markup.strong", {})
hi(0, "@markup.underline", { ctermfg = 248, fg = "#bdae93", underline = true })
hi(0, "@method", { link = "Function" })
hi(0, "@method.call", { link = "Function" })
hi(0, "@module", { link = "Include" })
hi(0, "@namespace", { link = "Include" })
hi(0, "@number.float", { link = "Float" })
hi(0, "@parameter", { link = "Identifier" })
hi(0, "@preproc", { link = "PreProc" })
hi(0, "@property", { link = "Field" })
hi(0, "@punctuation", { link = "Punctuation" })
hi(0, "@punctuation.bracket", { link = "Bracket" })
hi(0, "@punctuation.delimiter", { link = "Delimiter" })
hi(0, "@repeat", { link = "Repeat" })
hi(0, "@storageclass", { link = "StorageClass" })
hi(0, "@string.escape", { link = "Special" })
hi(0, "@string.special.url", { link = "Link" })
hi(0, "@tag.attribute", { link = "Field" })
hi(0, "@tag.delimiter", { link = "Delimiter" })
hi(0, "@text", { link = "Text" })
hi(0, "@text.danger", { link = "Error" })
hi(0, "@text.emphasis", { link = "Bold" })
hi(0, "@text.environment", { link = "PreProc" })
hi(0, "@text.environment.name", { link = "Delimiter" })
hi(0, "@text.literal", { link = "String" })
hi(0, "@text.math", { link = "Special" })
hi(0, "@text.note", { link = "SpecialComment" })
hi(0, "@text.reference", { link = "Identifier" })
hi(0, "@text.strike", { link = "Strikethrough" })
hi(0, "@text.strong", { link = "Bold" })
hi(0, "@text.title", { link = "Title" })
hi(0, "@text.title.1.marker.markdown", { link = "Special" })
hi(0, "@text.title.2.marker.markdown", { link = "Special" })
hi(0, "@text.title.3.marker.markdown", { link = "Special" })
hi(0, "@text.title.4.marker.markdown", { link = "Special" })
hi(0, "@text.title.5.marker.markdown", { link = "Special" })
hi(0, "@text.todo", { link = "Todo" })
hi(0, "@text.underline", { link = "Underlined" })
hi(0, "@text.uri", { link = "Link" })
hi(0, "@text.warning", { link = "WarningMsg" })
hi(0, "@type.definition", { link = "Typedef" })
hi(0, "@variable", { ctermfg = 223, fg = "#ebdbb2" })
hi(0, "@variable.builtin", { link = "Special" })
hi(0, "@variable.member", { link = "Field" })
hi(0, "@variable.parameter", { link = "Identifier" })
hi(0, "ALEError", { link = "GruvboxRedUnderline" })
hi(0, "ALEErrorSign", { link = "GruvboxRedSign" })
hi(0, "ALEInfo", { link = "GruvboxBlueUnderline" })
hi(0, "ALEInfoSign", { link = "GruvboxBlueSign" })
hi(0, "ALEVirtualTextError", { link = "GruvboxRed" })
hi(0, "ALEVirtualTextInfo", { link = "GruvboxBlue" })
hi(0, "ALEVirtualTextWarning", { link = "GruvboxYellow" })
hi(0, "ALEWarning", { link = "GruvboxYellowUnderline" })
hi(0, "ALEWarningSign", { link = "GruvboxYellowSign" })
hi(0, "Boolean", { link = "GruvboxPurple" })
hi(0, "Bracket", { link = "Punctuation" })
hi(0, "BufTabLineActive", { bg = "#504945", ctermbg = 239, ctermfg = 246, fg = "#a89984" })
hi(0, "BufTabLineCurrent", { bg = "#a89984", ctermbg = 246, ctermfg = 235, fg = "#282828" })
hi(0, "BufTabLineFill", { bg = "#282828", ctermbg = 235, ctermfg = 235, fg = "#282828" })
hi(0, "BufTabLineHidden", { bg = "#3c3836", ctermbg = 237, ctermfg = 243, fg = "#7c6f64" })
hi(0, "Character", { link = "GruvboxPurple" })
hi(0, "CmpItemAbbr", { link = "GruvboxFg0" })
hi(0, "CmpItemAbbrDefault", { fg = "#ebdbb2" })
hi(0, "CmpItemAbbrDeprecated", { link = "GruvboxFg1" })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#928374" })
hi(0, "CmpItemAbbrMatch", { link = "GruvboxBlueBold" })
hi(0, "CmpItemAbbrMatchDefault", { fg = "#ebdbb2" })
hi(0, "CmpItemAbbrMatchFuzzy", { link = "GruvboxBlueUnderline" })
hi(0, "CmpItemAbbrMatchFuzzyDefault", { fg = "#ebdbb2" })
hi(0, "CmpItemKindClass", { link = "GruvboxYellow" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstant", { link = "GruvboxOrange" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructor", { link = "GruvboxYellow" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindDefault", { fg = "#8cf8f7" })
hi(0, "CmpItemKindEnum", { link = "GruvboxYellow" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMember", { link = "GruvboxAqua" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindField", { link = "GruvboxBlue" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFile", { link = "GruvboxBlue" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunction", { link = "GruvboxBlue" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterface", { link = "GruvboxYellow" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKeyword", { link = "GruvboxPurple" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethod", { link = "GruvboxBlue" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModule", { link = "GruvboxBlue" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindProperty", { link = "GruvboxBlue" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippet", { link = "GruvboxGreen" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStruct", { link = "GruvboxYellow" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindText", { link = "GruvboxOrange" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameter", { link = "GruvboxYellow" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValue", { link = "GruvboxOrange" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "CmpItemMenu", { link = "GruvboxGray" })
hi(0, "CmpItemMenuDefault", { fg = "#ebdbb2" })
hi(0, "CocCodeLens", { link = "GruvboxGray" })
hi(0, "CocDiagnosticsError", { link = "GruvboxRed" })
hi(0, "CocDiagnosticsHint", { link = "GruvboxAqua" })
hi(0, "CocDiagnosticsInfo", { link = "GruvboxBlue" })
hi(0, "CocDiagnosticsWarning", { link = "GruvboxOrange" })
hi(0, "CocErrorFloat", { link = "GruvboxRed" })
hi(0, "CocErrorHighlight", { link = "GruvboxRedUnderline" })
hi(0, "CocErrorSign", { link = "GruvboxRedSign" })
hi(0, "CocHintFloat", { link = "GruvboxAqua" })
hi(0, "CocHintHighlight", { link = "GruvboxAquaUnderline" })
hi(0, "CocHintSign", { link = "GruvboxAquaSign" })
hi(0, "CocInfoFloat", { link = "GruvboxBlue" })
hi(0, "CocInfoHighlight", { link = "GruvboxBlueUnderline" })
hi(0, "CocInfoSign", { link = "GruvboxBlueSign" })
hi(0, "CocSearch", { link = "GruvboxAqua" })
hi(0, "CocSelectedText", { link = "GruvboxRed" })
hi(0, "CocWarningFloat", { link = "GruvboxOrange" })
hi(0, "CocWarningHighlight", { link = "GruvboxOrangeUnderline" })
hi(0, "CocWarningSign", { link = "GruvboxOrangeSign" })
hi(0, "CodeBlock", { link = "GruvboxAqua" })
hi(0, "ColorColumn", { bg = "#3c3836", ctermbg = 237 })
hi(0, "Comment", { ctermfg = 245, fg = "#928374" })
hi(0, "Conceal", { ctermfg = 109, fg = "#83a598" })
hi(0, "Conditional", { link = "GruvboxRed" })
hi(0, "Constant", { ctermfg = 175, fg = "#d3869b" })
hi(0, "CtrlPLinePre", { link = "GruvboxBg2" })
hi(0, "CtrlPMatch", { link = "GruvboxYellow" })
hi(0, "CtrlPMode1", { bg = "#504945", bold = true, ctermbg = 239, ctermfg = 109, fg = "#83a598" })
hi(0, "CtrlPMode2", { bg = "#83a598", bold = true, ctermbg = 109, ctermfg = 235, fg = "#282828" })
hi(0, "CtrlPNoEntries", { link = "GruvboxRed" })
hi(0, "CtrlPPrtBase", { link = "GruvboxBg2" })
hi(0, "CtrlPPrtCursor", { link = "GruvboxBlue" })
hi(0, "CtrlPStats", { bg = "#504945", bold = true, ctermbg = 239, ctermfg = 246, fg = "#a89984" })
hi(0, "Cursor", { reverse = true })
hi(0, "CursorColumn", { bg = "#3c3836", ctermbg = 237 })
hi(0, "CursorLine", { bg = "#3c3836", ctermbg = 237 })
hi(0, "CursorLineNr", { bg = "#3c3836", ctermbg = 237, ctermfg = 214, fg = "#fabd2f" })
hi(0, "DashboardCenter", { link = "GruvboxGreen" })
hi(0, "DashboardCenterIcon", { link = "GruvboxAqua" })
hi(0, "DashboardFooter", { link = "GruvboxPurple" })
hi(0, "DashboardHeader", { link = "GruvboxYellowBold" })
hi(0, "DashboardShortCut", { link = "GruvboxBlue" })
hi(0, "Define", { link = "GruvboxAqua" })
hi(0, "Delimiter", { ctermfg = 109, fg = "#83a598" })
hi(0, "DiagnosticError", { ctermfg = 167, fg = "#fb4934" })
hi(0, "DiagnosticHint", { ctermfg = 108, fg = "#8ec07c" })
hi(0, "DiagnosticInfo", { ctermfg = 109, fg = "#83a598" })
hi(0, "DiagnosticSignError", { link = "GruvboxRedSign" })
hi(0, "DiagnosticSignHint", { link = "GruvboxAquaSign" })
hi(0, "DiagnosticSignInfo", { link = "GruvboxBlueSign" })
hi(0, "DiagnosticSignWarn", { link = "GruvboxYellowSign" })
hi(0, "DiagnosticUnderlineError", { sp = "#fb4934", undercurl = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#8ec07c", undercurl = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#83a598", undercurl = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#fabd2f", undercurl = true })
hi(0, "DiagnosticWarn", { ctermfg = 214, fg = "#fabd2f" })
hi(0, "DiffAdd", { bg = "#282828", ctermbg = 235, ctermfg = 142, fg = "#b8bb26", reverse = true })
hi(0, "DiffChange", { bg = "#282828", ctermbg = 235, ctermfg = 108, fg = "#8ec07c", reverse = true })
hi(0, "DiffDelete", { bg = "#282828", ctermbg = 235, ctermfg = 167, fg = "#fb4934", reverse = true })
hi(0, "DiffText", { bg = "#282828", ctermbg = 235, ctermfg = 214, fg = "#fabd2f", reverse = true })
hi(0, "Directory", { bold = true, ctermfg = 142, fg = "#b8bb26" })
hi(0, "DirvishArg", { link = "GruvboxYellow" })
hi(0, "DirvishPathTail", { link = "GruvboxAqua" })
hi(0, "EasyMotionShade", { link = "GruvboxGray" })
hi(0, "EasyMotionTarget", { link = "GruvboxRedBold" })
hi(0, "EasyMotionTarget2First", { link = "GruvboxYellowBold" })
hi(0, "EasyMotionTarget2Second", { link = "GruvboxOrangeBold" })
hi(0, "Error", { bold = true, ctermfg = 167, fg = "#fb4934", reverse = true })
hi(0, "ErrorMsg", { bg = "#fb4934", bold = true, ctermbg = 167, ctermfg = 235, fg = "#282828" })
hi(0, "Exception", { link = "GruvboxRed" })
hi(0, "Field", { link = "GruvboxAqua" })
hi(0, "Float", { link = "GruvboxPurple" })
hi(0, "FoldColumn", { bg = "#3c3836", ctermbg = 237, ctermfg = 245, fg = "#928374" })
hi(0, "Folded", { bg = "#3c3836", ctermbg = 237, ctermfg = 245, fg = "#928374" })
hi(0, "Function", { bold = true, ctermfg = 142, fg = "#b8bb26" })
hi(0, "Fzf1", { bg = "#3c3836", ctermbg = 237, ctermfg = 109, fg = "#83a598" })
hi(0, "Fzf2", { bg = "#3c3836", ctermbg = 237, ctermfg = 208, fg = "#fe8019" })
hi(0, "Fzf3", { bg = "#3c3836", ctermbg = 237, ctermfg = 246, fg = "#a89984" })
hi(0, "GitGutterAdd", { link = "GruvboxGreenSign" })
hi(0, "GitGutterChange", { link = "GruvboxAquaSign" })
hi(0, "GitGutterChangeDelete", { link = "GruvboxAquaSign" })
hi(0, "GitGutterDelete", { link = "GruvboxRedSign" })
hi(0, "GitSignsAdd", { link = "GruvboxGreenSign" })
hi(0, "GitSignsChange", { link = "GruvboxOrangeSign" })
hi(0, "GitSignsDelete", { link = "GruvboxRedSign" })
hi(0, "GruvboxAqua", { ctermfg = 108, fg = "#8ec07c" })
hi(0, "GruvboxAquaBold", { bold = true, ctermfg = 108, fg = "#8ec07c" })
hi(0, "GruvboxAquaSign", { bg = "#3c3836", ctermbg = 237, ctermfg = 108, fg = "#8ec07c" })
hi(0, "GruvboxAquaUnderline", { sp = "#8ec07c", undercurl = true })
hi(0, "GruvboxBg0", { ctermfg = 235, fg = "#282828" })
hi(0, "GruvboxBg1", { ctermfg = 237, fg = "#3c3836" })
hi(0, "GruvboxBg2", { ctermfg = 239, fg = "#504945" })
hi(0, "GruvboxBg3", { ctermfg = 241, fg = "#665c54" })
hi(0, "GruvboxBg4", { ctermfg = 243, fg = "#7c6f64" })
hi(0, "GruvboxBlue", { ctermfg = 109, fg = "#83a598" })
hi(0, "GruvboxBlueBold", { bold = true, ctermfg = 109, fg = "#83a598" })
hi(0, "GruvboxBlueSign", { bg = "#3c3836", ctermbg = 237, ctermfg = 109, fg = "#83a598" })
hi(0, "GruvboxBlueUnderline", { sp = "#83a598", undercurl = true })
hi(0, "GruvboxFg0", { ctermfg = 229, fg = "#fbf1c7" })
hi(0, "GruvboxFg1", { ctermfg = 223, fg = "#ebdbb2" })
hi(0, "GruvboxFg2", { ctermfg = 250, fg = "#d5c4a1" })
hi(0, "GruvboxFg3", { ctermfg = 248, fg = "#bdae93" })
hi(0, "GruvboxFg4", { ctermfg = 246, fg = "#a89984" })
hi(0, "GruvboxGray", { ctermfg = 245, fg = "#928374" })
hi(0, "GruvboxGreen", { ctermfg = 142, fg = "#b8bb26" })
hi(0, "GruvboxGreenBold", { bold = true, ctermfg = 142, fg = "#b8bb26" })
hi(0, "GruvboxGreenSign", { bg = "#3c3836", ctermbg = 237, ctermfg = 142, fg = "#b8bb26" })
hi(0, "GruvboxGreenUnderline", { sp = "#b8bb26", undercurl = true })
hi(0, "GruvboxOrange", { ctermfg = 208, fg = "#fe8019" })
hi(0, "GruvboxOrangeBold", { bold = true, ctermfg = 208, fg = "#fe8019" })
hi(0, "GruvboxOrangeSign", { bg = "#3c3836", ctermbg = 237, ctermfg = 208, fg = "#fe8019" })
hi(0, "GruvboxOrangeUnderline", { sp = "#fe8019", undercurl = true })
hi(0, "GruvboxPurple", { ctermfg = 175, fg = "#d3869b" })
hi(0, "GruvboxPurpleBold", { bold = true, ctermfg = 175, fg = "#d3869b" })
hi(0, "GruvboxPurpleSign", { bg = "#3c3836", ctermbg = 237, ctermfg = 175, fg = "#d3869b" })
hi(0, "GruvboxPurpleUnderline", { sp = "#d3869b", undercurl = true })
hi(0, "GruvboxRed", { ctermfg = 167, fg = "#fb4934" })
hi(0, "GruvboxRedBold", { bold = true, ctermfg = 167, fg = "#fb4934" })
hi(0, "GruvboxRedSign", { bg = "#3c3836", ctermbg = 237, ctermfg = 167, fg = "#fb4934" })
hi(0, "GruvboxRedUnderline", { sp = "#fb4934", undercurl = true })
hi(0, "GruvboxYellow", { ctermfg = 214, fg = "#fabd2f" })
hi(0, "GruvboxYellowBold", { bold = true, ctermfg = 214, fg = "#fabd2f" })
hi(0, "GruvboxYellowSign", { bg = "#3c3836", ctermbg = 237, ctermfg = 214, fg = "#fabd2f" })
hi(0, "GruvboxYellowUnderline", { sp = "#fabd2f", undercurl = true })
hi(0, "H1", { link = "GruvboxGreenBold" })
hi(0, "H2", { link = "GruvboxGreenBold" })
hi(0, "H3", { link = "GruvboxGreen" })
hi(0, "H4", { link = "GruvboxGreen" })
hi(0, "H5", { link = "GruvboxGreen" })
hi(0, "H6", { link = "GruvboxGreen" })
hi(0, "Identifier", { ctermfg = 223, fg = "#ebdbb2" })
hi(0, "IncSearch", { bg = "#282828", ctermbg = 235, ctermfg = 208, fg = "#fe8019", reverse = true })
hi(0, "Include", { link = "GruvboxAqua" })
hi(0, "IndentGuidesEven", { bg = "#3c3836", ctermbg = 237, ctermfg = 235, fg = "#282828" })
hi(0, "IndentGuidesOdd", { bg = "#504945", ctermbg = 239, ctermfg = 235, fg = "#282828" })
hi(0, "Keyword", { link = "GruvboxRed" })
hi(0, "Label", { link = "GruvboxRed" })
hi(0, "LineNr", { ctermfg = 243, fg = "#7c6f64" })
hi(0, "Link", { ctermfg = 175, fg = "#d3869b", underline = true })
hi(0, "LspCodeLens", { link = "GruvboxGray" })
hi(0, "LspDiagnosticsDefaultError", { link = "GruvboxRed" })
hi(0, "LspDiagnosticsDefaultHint", { link = "GruvboxAqua" })
hi(0, "LspDiagnosticsDefaultInformation", { link = "GruvboxBlue" })
hi(0, "LspDiagnosticsDefaultWarning", { link = "GruvboxYellow" })
hi(0, "LspDiagnosticsSignError", { link = "GruvboxRedSign" })
hi(0, "LspDiagnosticsSignHint", { link = "GruvboxAquaSign" })
hi(0, "LspDiagnosticsSignInformation", { link = "GruvboxBlueSign" })
hi(0, "LspDiagnosticsSignWarning", { link = "GruvboxYellowSign" })
hi(0, "LspDiagnosticsUnderlineError", { link = "GruvboxRedUnderline" })
hi(0, "LspDiagnosticsUnderlineHint", { link = "GruvboxAquaUnderline" })
hi(0, "LspDiagnosticsUnderlineInformation", { link = "GruvboxBlueUnderline" })
hi(0, "LspDiagnosticsUnderlineWarning", { link = "GruvboxYellowUnderline" })
hi(0, "LspReferenceRead", { link = "GruvboxYellowBold" })
hi(0, "LspReferenceText", { link = "GruvboxYellowBold" })
hi(0, "LspReferenceWrite", { link = "GruvboxOrangeBold" })
hi(0, "Macro", { link = "GruvboxAqua" })
hi(0, "MatchParen", { bg = "#665c54", bold = true, ctermbg = 241 })
hi(0, "ModeMsg", { bold = true, ctermfg = 214, fg = "#fabd2f" })
hi(0, "MoreMsg", { bold = true, ctermfg = 214, fg = "#fabd2f" })
hi(0, "NERDTreeCWD", { link = "GruvboxGreen" })
hi(0, "NERDTreeClosable", { link = "GruvboxOrange" })
hi(0, "NERDTreeDir", { link = "GruvboxAqua" })
hi(0, "NERDTreeDirSlash", { link = "GruvboxAqua" })
hi(0, "NERDTreeExecFile", { link = "GruvboxYellow" })
hi(0, "NERDTreeFile", { link = "GruvboxFg1" })
hi(0, "NERDTreeHelp", { link = "GruvboxFg1" })
hi(0, "NERDTreeOpenable", { link = "GruvboxOrange" })
hi(0, "NERDTreeToggleOff", { link = "GruvboxRed" })
hi(0, "NERDTreeToggleOn", { link = "GruvboxGreen" })
hi(0, "NERDTreeUp", { link = "GruvboxGray" })
hi(0, "Noise", { link = "Punctuation" })
hi(0, "NonText", { ctermfg = 239, fg = "#504945" })
hi(0, "Normal", { bg = "#282828", ctermbg = 235, ctermfg = 223, fg = "#ebdbb2" })
hi(0, "Number", { link = "GruvboxPurple" })
hi(0, "Operator", { ctermfg = 208, fg = "#fe8019" })
hi(0, "Pmenu", { bg = "#504945", ctermbg = 239, ctermfg = 223, fg = "#ebdbb2" })
hi(0, "PmenuSbar", { bg = "#504945", ctermbg = 239 })
hi(0, "PmenuSel", { bg = "#83a598", blend = 0, bold = true, ctermbg = 109, ctermfg = 239, fg = "#504945" })
hi(0, "PmenuThumb", { bg = "#7c6f64", ctermbg = 243 })
hi(0, "PreCondit", { link = "GruvboxAqua" })
hi(0, "PreProc", { ctermfg = 108, fg = "#8ec07c" })
hi(0, "Punctuation", { link = "GruvboxBlue" })
hi(0, "Question", { bold = true, ctermfg = 208, fg = "#fe8019" })
hi(0, "QuickFixLine", { bg = "#fabd2f", bold = true, ctermbg = 214, ctermfg = 235, fg = "#282828" })
hi(0, "Quote", { link = "GruvboxFg3" })
hi(0, "Repeat", { link = "GruvboxRed" })
hi(0, "Search", { bg = "#282828", ctermbg = 235, ctermfg = 214, fg = "#fabd2f", reverse = true })
hi(0, "ShowMarksHLl", { link = "GruvboxBlueSign" })
hi(0, "ShowMarksHLm", { link = "GruvboxBlueSign" })
hi(0, "ShowMarksHLo", { link = "GruvboxBlueSign" })
hi(0, "ShowMarksHLu", { link = "GruvboxBlueSign" })
hi(0, "SignColumn", { bg = "#3c3836", ctermbg = 237 })
hi(0, "SignatureMarkText", { link = "GruvboxBlueSign" })
hi(0, "SignatureMarkerText", { link = "GruvboxPurpleSign" })
hi(0, "SignifySignAdd", { link = "GruvboxGreenSign" })
hi(0, "SignifySignChange", { link = "GruvboxAquaSign" })
hi(0, "SignifySignDelete", { link = "GruvboxRedSign" })
hi(0, "Sneak", { link = "Search" })
hi(0, "SneakLabel", { link = "Search" })
hi(0, "Special", { ctermfg = 208, fg = "#fe8019" })
hi(0, "SpecialKey", { ctermfg = 246, fg = "#a89984" })
hi(0, "SpellBad", { sp = "#fb4934", undercurl = true })
hi(0, "SpellCap", { sp = "#83a598", undercurl = true })
hi(0, "SpellLocal", { sp = "#8ec07c", undercurl = true })
hi(0, "SpellRare", { sp = "#d3869b", undercurl = true })
hi(0, "StartifyBracket", { link = "GruvboxFg3" })
hi(0, "StartifyFile", { link = "GruvboxFg1" })
hi(0, "StartifyFooter", { link = "GruvboxBg2" })
hi(0, "StartifyHeader", { link = "GruvboxOrange" })
hi(0, "StartifyNumber", { link = "GruvboxBlue" })
hi(0, "StartifyPath", { link = "GruvboxGray" })
hi(0, "StartifySection", { link = "GruvboxYellow" })
hi(0, "StartifySlash", { link = "GruvboxGray" })
hi(0, "StartifySpecial", { link = "GruvboxBg2" })
hi(0, "Statement", { ctermfg = 167, fg = "#fb4934" })
hi(0, "StatusLine", { bg = "#ebdbb2", ctermbg = 223, ctermfg = 239, fg = "#504945", reverse = true })
hi(0, "StatusLineNC", { bg = "#a89984", ctermbg = 246, ctermfg = 237, fg = "#3c3836", reverse = true })
hi(0, "StorageClass", { link = "GruvboxYellow" })
hi(0, "String", { ctermfg = 142, fg = "#b8bb26" })
hi(0, "Structure", { link = "GruvboxYellow" })
hi(0, "SyntasticError", { link = "GruvboxRedUnderline" })
hi(0, "SyntasticErrorSign", { link = "GruvboxRedSign" })
hi(0, "SyntasticWarning", { link = "GruvboxYellowUnderline" })
hi(0, "SyntasticWarningSign", { link = "GruvboxYellowSign" })
hi(0, "TabLine", { link = "TabLineFill" })
hi(0, "TabLineFill", { bg = "#3c3836", ctermbg = 237, ctermfg = 243, fg = "#7c6f64" })
hi(0, "TabLineSel", { bg = "#3c3836", ctermbg = 237, ctermfg = 142, fg = "#b8bb26" })
hi(0, "Tag", { link = "GruvboxGreen" })
hi(0, "TelescopeMatching", { link = "GruvboxBlue" })
hi(0, "TelescopeMultiSelection", { link = "GruvboxGray" })
hi(0, "TelescopeNormal", { link = "GruvboxFg1" })
hi(0, "TelescopePreviewBorder", { link = "TelescopeNormal" })
hi(0, "TelescopePrompt", { link = "TelescopeNormal" })
hi(0, "TelescopePromptBorder", { link = "TelescopeNormal" })
hi(0, "TelescopePromptPrefix", { link = "GruvboxRed" })
hi(0, "TelescopeResultsBorder", { link = "TelescopeNormal" })
hi(0, "TelescopeSelection", { link = "GruvboxOrangeBold" })
hi(0, "TelescopeSelectionCaret", { link = "GruvboxRed" })
hi(0, "Text", { link = "GruvboxFg1" })
hi(0, "Title", { bold = true, ctermfg = 142, fg = "#b8bb26" })
hi(0, "Todo", { bold = true, ctermfg = 223, fg = "#ebdbb2" })
hi(0, "Type", { ctermfg = 214, fg = "#fabd2f" })
hi(0, "Typedef", { link = "GruvboxYellow" })
hi(0, "Underlined", { ctermfg = 248, fg = "#bdae93", underline = true })
hi(0, "VertSplit", { bg = "#282828", ctermbg = 235, ctermfg = 241, fg = "#665c54" })
hi(0, "Visual", { bg = "#665c54", ctermbg = 241, reverse = true })
hi(0, "WarningMsg", { bold = true, ctermfg = 167, fg = "#fb4934" })
hi(0, "WildMenu", { bg = "#504945", bold = true, ctermbg = 239, ctermfg = 109, fg = "#83a598" })
hi(0, "clojureStringEscape", { link = "Special" })
hi(0, "coffeeBracket", { link = "Bracket" })
hi(0, "coffeeCurly", { link = "Bracket" })
hi(0, "coffeeExtendedOp", { link = "Operator" })
hi(0, "coffeeObjAssign", { link = "Field" })
hi(0, "coffeeObject", { link = "Field" })
hi(0, "coffeeParen", { link = "Bracket" })
hi(0, "coffeeSpecialOp", { link = "Operator" })
hi(0, "csBraces", { link = "Bracket" })
hi(0, "csEndColon", { link = "Punctuation" })
hi(0, "csInterpolationAlignDel", { link = "Punctuation" })
hi(0, "csInterpolationDelimiter", { link = "Punctuation" })
hi(0, "csInterpolationFormat", { link = "Special" })
hi(0, "csInterpolationFormatDel", { link = "Punctuation" })
hi(0, "csLogicSymbols", { link = "Operator" })
hi(0, "csOpSymbols", { link = "Operator" })
hi(0, "csParens", { link = "Bracket" })
hi(0, "csStorage", { link = "Keyword" })
hi(0, "csUnspecifiedStatement", { link = "Statement" })
hi(0, "cssAtRule", { link = "Punctuation" })
hi(0, "cssAttrComma", { link = "Punctuation" })
hi(0, "cssBraces", { link = "Punctuation" })
hi(0, "cssClassName", { link = "Tag" })
hi(0, "cssClassNameDot", { link = "Operator" })
hi(0, "cssFunctionComma", { link = "Special" })
hi(0, "cssFunctionName", { link = "Special" })
hi(0, "cssIdentifier", { link = "Identifier" })
hi(0, "cssImportant", { link = "Keyword" })
hi(0, "cssProp", { link = "Field" })
hi(0, "cssPseudoClassId", { link = "Tag" })
hi(0, "cssSelectorOp", { link = "Punctuation" })
hi(0, "cssSelectorOp2", { link = "Punctuation" })
hi(0, "cssVendor", { link = "Field" })
hi(0, "debugBreakpoint", { link = "GruvboxRedSign" })
hi(0, "debugPC", { bg = "#076678", ctermbg = 24 })
hi(0, "diffAdded", { link = "GruvboxGreen" })
hi(0, "diffChanged", { link = "GruvboxAqua" })
hi(0, "diffFile", { link = "GruvboxOrange" })
hi(0, "diffLine", { link = "GruvboxBlue" })
hi(0, "diffNewFile", { link = "GruvboxYellow" })
hi(0, "diffRemoved", { link = "GruvboxRed" })
hi(0, "docbkKeyword", { link = "Tag" })
hi(0, "docbkTitle", { bg = "#282828", bold = true, ctermbg = 235, ctermfg = 223, fg = "#ebdbb2" })
hi(0, "dtdAttrType", { link = "Type" })
hi(0, "dtdCard", { link = "Operator" })
hi(0, "dtdEnum", { link = "Constant" })
hi(0, "dtdFunction", { link = "Punctuation" })
hi(0, "dtdParamEntityDPunct", { link = "Punctuation" })
hi(0, "dtdParamEntityPunct", { link = "Punctuation" })
hi(0, "dtdString", { link = "String" })
hi(0, "dtdTag", { link = "Field" })
hi(0, "dtdTagName", { link = "Special" })
hi(0, "elixirDocString", { link = "Comment" })
hi(0, "elixirInterpolationDelimiter", { link = "Punctuation" })
hi(0, "elixirModuleDeclaration", { link = "Typedef" })
hi(0, "elixirStringDelimiter", { link = "String" })
hi(0, "fugitiveHash", { link = "GruvboxBlue" })
hi(0, "gitcommitDiscardedFile", { link = "GruvboxRed" })
hi(0, "gitcommitSelectedFile", { link = "GruvboxGreen" })
hi(0, "goConst", { link = "StorageClass" })
hi(0, "goImport", { link = "Include" })
hi(0, "goParen", { link = "Bracket" })
hi(0, "haskellAssocType", { link = "Type" })
hi(0, "haskellBacktick", { link = "Special" })
hi(0, "haskellBottom", { link = "Keyword" })
hi(0, "haskellChar", { link = "Character" })
hi(0, "haskellConditional", { link = "Keyword" })
hi(0, "haskellDecl", { link = "Keyword" })
hi(0, "haskellDeclKeyword", { link = "Keyword" })
hi(0, "haskellDefault", { link = "Keyword" })
hi(0, "haskellDelimiter", { link = "Delimiter" })
hi(0, "haskellDeriveKeyword", { link = "Keyword" })
hi(0, "haskellFloat", { link = "Float" })
hi(0, "haskellForall", { link = "Operator" })
hi(0, "haskellForeignKeywords", { link = "Include" })
hi(0, "haskellIdentifier", { link = "Identifier" })
hi(0, "haskellImportKeywords", { link = "Include" })
hi(0, "haskellInfix", { link = "Keyword" })
hi(0, "haskellKeyword", { link = "Keyword" })
hi(0, "haskellLet", { link = "Keyword" })
hi(0, "haskellLiquid", { link = "Comment" })
hi(0, "haskellNumber", { link = "Number" })
hi(0, "haskellOperators", { link = "Operator" })
hi(0, "haskellPatternKeyword", { link = "Keyword" })
hi(0, "haskellPragma", { link = "PreProc" })
hi(0, "haskellPreProc", { link = "PreProc" })
hi(0, "haskellQuasiQuoted", { link = "String" })
hi(0, "haskellQuote", { link = "String" })
hi(0, "haskellQuotedType", { link = "Type" })
hi(0, "haskellRecursiveDo", { link = "Keyword" })
hi(0, "haskellSeparator", { link = "Punctuation" })
hi(0, "haskellShebang", { link = "Comment" })
hi(0, "haskellTH", { link = "Boolean" })
hi(0, "haskellType", { link = "Type" })
hi(0, "haskellTypeRoles", { link = "Keyword" })
hi(0, "haskellWhere", { link = "Keyword" })
hi(0, "htmlArg", { link = "Field" })
hi(0, "htmlBold", { bg = "#282828", bold = true, ctermbg = 235, ctermfg = 223, fg = "#ebdbb2" })
hi(0, "htmlBoldItalic", { bg = "#282828", bold = true, ctermbg = 235, ctermfg = 223, fg = "#ebdbb2" })
hi(0, "htmlBoldUnderline", { bg = "#282828", bold = true, ctermbg = 235, ctermfg = 223, fg = "#ebdbb2", underline = true })
hi(0, "htmlBoldUnderlineItalic", { bg = "#282828", bold = true, ctermbg = 235, ctermfg = 223, fg = "#ebdbb2", underline = true })
hi(0, "htmlEndTag", { link = "Punctuation" })
hi(0, "htmlItalic", { bg = "#282828", ctermbg = 235, ctermfg = 223, fg = "#ebdbb2" })
hi(0, "htmlLink", { ctermfg = 246, fg = "#a89984", underline = true })
hi(0, "htmlSpecialChar", { link = "Special" })
hi(0, "htmlSpecialTagName", { link = "Special" })
hi(0, "htmlTag", { link = "Punctuation" })
hi(0, "htmlTagN", { link = "Normal" })
hi(0, "htmlTagName", { link = "Tag" })
hi(0, "htmlUnderline", { bg = "#282828", ctermbg = 235, ctermfg = 223, fg = "#ebdbb2", underline = true })
hi(0, "htmlUnderlineItalic", { bg = "#282828", ctermbg = 235, ctermfg = 223, fg = "#ebdbb2", underline = true })
hi(0, "iCursor", { link = "Cursor" })
hi(0, "javaDocParam", { link = "Type" })
hi(0, "javaDocTags", { link = "Keyword" })
hi(0, "javaOperator", { link = "Operator" })
hi(0, "javaParen", { link = "Bracket" })
hi(0, "javaParen1", { link = "javaParen" })
hi(0, "javaParen2", { link = "javaParen" })
hi(0, "javaParen3", { link = "javaParen" })
hi(0, "javaParen4", { link = "javaParen" })
hi(0, "javaParen5", { link = "javaParen" })
hi(0, "javaScriptBraces", { link = "Bracket" })
hi(0, "javascriptArrowFunc", { link = "Punctuation" })
hi(0, "javascriptArrowFuncArg", { link = "Identifier" })
hi(0, "javascriptBOMHistoryProp", { link = "javascriptProp" })
hi(0, "javascriptBOMLocationProp", { link = "javascriptProp" })
hi(0, "javascriptBOMNavigatorProp", { link = "javascriptProp" })
hi(0, "javascriptBOMNetworkProp", { link = "javascriptProp" })
hi(0, "javascriptBOMWindowProp", { link = "javascriptProp" })
hi(0, "javascriptBrackets", { link = "Bracket" })
hi(0, "javascriptBroadcastProp", { link = "javascriptProp" })
hi(0, "javascriptComma", { link = "Punctuation" })
hi(0, "javascriptCryptoProp", { link = "javascriptProp" })
hi(0, "javascriptDOMDocProp", { link = "javascriptProp" })
hi(0, "javascriptDOMEventProp", { link = "javascriptProp" })
hi(0, "javascriptDOMFormProp", { link = "javascriptProp" })
hi(0, "javascriptDOMNodeProp", { link = "javascriptProp" })
hi(0, "javascriptDOMStorageProp", { link = "javascriptProp" })
hi(0, "javascriptDataViewProp", { link = "javascriptProp" })
hi(0, "javascriptDocName", { link = "Field" })
hi(0, "javascriptDocNotation", { link = "Keyword" })
hi(0, "javascriptDocParam", { link = "Identifier" })
hi(0, "javascriptDocParamName", { link = "Field" })
hi(0, "javascriptDocParamType", { link = "Type" })
hi(0, "javascriptDocTags", { link = "Keyword" })
hi(0, "javascriptDotNotation", { link = "Punctuation" })
hi(0, "javascriptES6MapProp", { link = "javascriptProp" })
hi(0, "javascriptES6SetProp", { link = "javascriptProp" })
hi(0, "javascriptEncodingProp", { link = "javascriptProp" })
hi(0, "javascriptEndColons", { link = "Punctuation" })
hi(0, "javascriptFileReaderProp", { link = "javascriptProp" })
hi(0, "javascriptFuncArg", { link = "Identifier" })
hi(0, "javascriptGlobal", { link = "Special" })
hi(0, "javascriptIdentifierName", { link = "Identifier" })
hi(0, "javascriptLabel", { link = "Field" })
hi(0, "javascriptMathStaticProp", { link = "javascriptProp" })
hi(0, "javascriptMethod", { link = "Function" })
hi(0, "javascriptNull", { link = "Constant" })
hi(0, "javascriptNumber", { link = "Number" })
hi(0, "javascriptNumberStaticProp", { link = "javascriptProp" })
hi(0, "javascriptObjectLabelColon", { link = "Punctuation" })
hi(0, "javascriptOpSymbol", { link = "Operator" })
hi(0, "javascriptOpSymbols", { link = "Operator" })
hi(0, "javascriptOperator", { link = "Operator" })
hi(0, "javascriptParenObjectLiteral", { link = "Bracket" })
hi(0, "javascriptParenTagLiteral", { link = "Bracket" })
hi(0, "javascriptParens", { link = "Bracket" })
hi(0, "javascriptPaymentAddressProp", { link = "javascriptProp" })
hi(0, "javascriptPaymentProp", { link = "javascriptProp" })
hi(0, "javascriptPaymentResponseProp", { link = "javascriptProp" })
hi(0, "javascriptPaymentShippingOptionProp", { link = "javascriptProp" })
hi(0, "javascriptProp", { link = "Field" })
hi(0, "javascriptRegExpProp", { link = "javascriptProp" })
hi(0, "javascriptRegExpStaticProp", { link = "javascriptProp" })
hi(0, "javascriptRequestProp", { link = "javascriptProp" })
hi(0, "javascriptResponseProp", { link = "javascriptProp" })
hi(0, "javascriptServiceWorkerProp", { link = "javascriptProp" })
hi(0, "javascriptSymbolProp", { link = "javascriptProp" })
hi(0, "javascriptSymbolStaticProp", { link = "javascriptProp" })
hi(0, "javascriptTemplateSubstitution", { link = "Punctuation" })
hi(0, "javascriptTypedArrayStaticProp", { link = "javascriptProp" })
hi(0, "javascriptURLUtilsProp", { link = "javascriptProp" })
hi(0, "javascriptVariable", { link = "StorageClass" })
hi(0, "javascriptXHRProp", { link = "javascriptProp" })
hi(0, "jsArrowFunction", { link = "Punctuation" })
hi(0, "jsDocParam", { link = "Field" })
hi(0, "jsDocTags", { link = "Keyword" })
hi(0, "jsNull", { link = "Special" })
hi(0, "jsObjectKey", { link = "Field" })
hi(0, "jsObjectProp", { link = "Field" })
hi(0, "jsonBraces", { link = "Punctuation" })
hi(0, "jsonKeyword", { link = "Field" })
hi(0, "jsonKeywordMatch", { link = "Punctuation" })
hi(0, "jsonQuote", { link = "String" })
hi(0, "jsonString", { link = "String" })
hi(0, "jsxAttrib", { link = "Field" })
hi(0, "jsxBraces", { link = "Special" })
hi(0, "jsxClosePunct", { link = "Punctuation" })
hi(0, "jsxCloseString", { link = "Punctuation" })
hi(0, "jsxComponentName", { link = "Type" })
hi(0, "jsxEqual", { link = "Operator" })
hi(0, "jsxOpenPunct", { link = "Punctuation" })
hi(0, "jsxTagName", { link = "Tag" })
hi(0, "lCursor", { reverse = true })
hi(0, "luaBraces", { link = "Bracket" })
hi(0, "luaComma", { link = "Punctuation" })
hi(0, "luaFuncKeyword", { link = "Keyword" })
hi(0, "luaParen", { link = "Bracket" })
hi(0, "luaStringLongTag", { link = "Special" })
hi(0, "luaTable", { link = "Bracket" })
hi(0, "mailQuoted1", { link = "GruvboxAqua" })
hi(0, "mailQuoted2", { link = "GruvboxPurple" })
hi(0, "mailQuoted3", { link = "GruvboxYellow" })
hi(0, "mailQuoted4", { link = "GruvboxGreen" })
hi(0, "mailQuoted5", { link = "GruvboxRed" })
hi(0, "mailQuoted6", { link = "GruvboxOrange" })
hi(0, "mailSignature", { link = "Comment" })
hi(0, "markdownBlockquote", { link = "Quote" })
hi(0, "markdownBold", { bold = true, ctermfg = 248, fg = "#bdae93" })
hi(0, "markdownBoldItalic", { bold = true, ctermfg = 248, fg = "#bdae93" })
hi(0, "markdownCode", { link = "CodeBlock" })
hi(0, "markdownCodeBlock", { link = "CodeBlock" })
hi(0, "markdownCodeDelimiter", { link = "Punctuation" })
hi(0, "markdownH1", { link = "H1" })
hi(0, "markdownH2", { link = "H2" })
hi(0, "markdownH3", { link = "H3" })
hi(0, "markdownH4", { link = "H4" })
hi(0, "markdownH5", { link = "H5" })
hi(0, "markdownH6", { link = "H6" })
hi(0, "markdownHeadingDelimiter", { link = "GruvboxGreen" })
hi(0, "markdownHeadingRule", { link = "Punctuation" })
hi(0, "markdownIdDeclaration", { link = "Identifier" })
hi(0, "markdownItalic", { ctermfg = 248, fg = "#bdae93" })
hi(0, "markdownLinkDelimiter", { link = "Punctuation" })
hi(0, "markdownLinkText", { link = "Identifier" })
hi(0, "markdownLinkTextDelimiter", { link = "Punctuation" })
hi(0, "markdownListMarker", { link = "Punctuation" })
hi(0, "markdownOrderedListMarker", { link = "Punctuation" })
hi(0, "markdownRule", { link = "Punctuation" })
hi(0, "markdownUrl", { link = "Link" })
hi(0, "markdownUrlDelimiter", { link = "Punctuation" })
hi(0, "markdownUrlTitleDelimiter", { link = "Punctuation" })
hi(0, "moonFunction", { link = "Punctuation" })
hi(0, "moonLuaFunc", { link = "Function" })
hi(0, "moonObjAssign", { link = "Field" })
hi(0, "multiple_cursors_cursor", { reverse = true })
hi(0, "multiple_cursors_visual", { bg = "#504945", ctermbg = 239 })
hi(0, "netrwClassify", { link = "GruvboxAqua" })
hi(0, "netrwCmdSep", { link = "GruvboxFg3" })
hi(0, "netrwComment", { link = "GruvboxGray" })
hi(0, "netrwDir", { link = "GruvboxAqua" })
hi(0, "netrwExe", { link = "GruvboxYellow" })
hi(0, "netrwHelpCmd", { link = "GruvboxAqua" })
hi(0, "netrwLink", { link = "GruvboxGray" })
hi(0, "netrwList", { link = "GruvboxBlue" })
hi(0, "netrwSymLink", { link = "GruvboxFg1" })
hi(0, "netrwVersion", { link = "GruvboxGreen" })
hi(0, "objcDirective", { link = "Keyword" })
hi(0, "objcObjDef", { link = "Keyword" })
hi(0, "objcPropertyAttribute", { link = "Field" })
hi(0, "objcTypeModifier", { link = "GruvboxRed" })
hi(0, "ocamlArrow", { link = "Operator" })
hi(0, "ocamlConstructor", { link = "Type" })
hi(0, "ocamlInfixOpKeyword", { link = "Keyword" })
hi(0, "ocamlKeyChar", { link = "Operator" })
hi(0, "ocamlOperator", { link = "Operator" })
hi(0, "purescriptImportKeyword", { link = "Include" })
hi(0, "purescriptModuleName", { link = "Identifier" })
hi(0, "pythonDecorator", { link = "Operator" })
hi(0, "pythonDot", { link = "Operator" })
hi(0, "rubyDefinedOperator", { link = "Keyword" })
hi(0, "rubyInterpolationDelimiter", { link = "Macro" })
hi(0, "rubyStringDelimiter", { link = "String" })
hi(0, "rustFoldBraces", { link = "Bracket" })
hi(0, "rustSelf", { link = "Special" })
hi(0, "rustSigil", { link = "Operator" })
hi(0, "scalaAnnotation", { link = "Special" })
hi(0, "scalaCapitalWord", { link = "Type" })
hi(0, "scalaCaseFollowing", { link = "Identifier" })
hi(0, "scalaCommentAnnotation", { link = "Keyword" })
hi(0, "scalaCommentCodeBlock", { link = "CodeBlock" })
hi(0, "scalaDocLinks", { link = "Link" })
hi(0, "scalaEscapedChar", { link = "Special" })
hi(0, "scalaExternal", { link = "Include" })
hi(0, "scalaFInterpolation", { link = "Operator" })
hi(0, "scalaFString", { link = "String" })
hi(0, "scalaIString", { link = "String" })
hi(0, "scalaInstanceDeclaration", { link = "Type" })
hi(0, "scalaInterpolation", { link = "Operator" })
hi(0, "scalaInterpolationBoundary", { link = "Operator" })
hi(0, "scalaInterpolationBrackets", { link = "String" })
hi(0, "scalaKeyword", { link = "Keyword" })
hi(0, "scalaKeywordModifier", { link = "Keyword" })
hi(0, "scalaMultilineComment", { link = "Comment" })
hi(0, "scalaNameDefinition", { link = "Identifier" })
hi(0, "scalaNumber", { link = "Number" })
hi(0, "scalaOperator", { link = "Operator" })
hi(0, "scalaParamAnnotationValue", { link = "Field" })
hi(0, "scalaParameterAnnotation", { link = "Keyword" })
hi(0, "scalaShebang", { link = "Comment" })
hi(0, "scalaSpecial", { link = "Special" })
hi(0, "scalaSquareBrackets", { link = "Identifier" })
hi(0, "scalaSquareBracketsBrackets", { link = "Identifier" })
hi(0, "scalaString", { link = "String" })
hi(0, "scalaTrailingComment", { link = "Comment" })
hi(0, "scalaTripleFString", { link = "String" })
hi(0, "scalaTripleIString", { link = "String" })
hi(0, "scalaTripleString", { link = "String" })
hi(0, "scalaTypeAnnotation", { link = "Identifier" })
hi(0, "scalaTypeAnnotationParameter", { link = "Special" })
hi(0, "scalaTypeDeclaration", { link = "Typedef" })
hi(0, "scalaTypeExtension", { link = "Identifier" })
hi(0, "scalaTypeOperator", { link = "Identifier" })
hi(0, "scalaTypePostExtension", { link = "Operator" })
hi(0, "scalaTypeTypeExtension", { link = "Identifier" })
hi(0, "scalaTypeTypePostDeclaration", { link = "Typedef" })
hi(0, "scalaTypeTypePostExtension", { link = "Operator" })
hi(0, "typescriptAssign", { link = "Punctuation" })
hi(0, "typescriptBinaryOp", { link = "Operator" })
hi(0, "typescriptBraces", { link = "Punctuation" })
hi(0, "typescriptCastKeyword", { link = "Keyword" })
hi(0, "typescriptDocNotation", { link = "Keyword" })
hi(0, "typescriptDocParam", { link = "Field" })
hi(0, "typescriptDocTags", { link = "Keyword" })
hi(0, "typescriptEndColons", { link = "Punctuation" })
hi(0, "typescriptExport", { link = "Include" })
hi(0, "typescriptImport", { link = "Include" })
hi(0, "typescriptInterfaceName", { link = "Typedef" })
hi(0, "typescriptKeywordOp", { link = "Operator" })
hi(0, "typescriptMember", { link = "Field" })
hi(0, "typescriptObjectColon", { link = "Punctuation" })
hi(0, "typescriptObjectLabel", { link = "Field" })
hi(0, "typescriptParens", { link = "Punctuation" })
hi(0, "typescriptTernary", { link = "Operator" })
hi(0, "typescriptTypeAnnotation", { link = "Punctuation" })
hi(0, "typescriptVariable", { link = "Type" })
hi(0, "vCursor", { link = "Cursor" })
hi(0, "vimBracket", { link = "GruvboxFg3" })
hi(0, "vimCommand", { link = "Keyword" })
hi(0, "vimCommentTitle", { bold = true, ctermfg = 246, fg = "#a89984" })
hi(0, "vimContinue", { link = "GruvboxFg3" })
hi(0, "vimEcho", { link = "GruvboxFg3" })
hi(0, "vimFuncSID", { link = "Variable" })
hi(0, "vimFunction", { link = "Variable" })
hi(0, "vimMapModKey", { link = "Special" })
hi(0, "vimNotation", { link = "Special" })
hi(0, "vimOperParen", { link = "GruvboxFg3" })
hi(0, "vimOption", { link = "Special" })
hi(0, "vimParenSep", { link = "GruvboxFg3" })
hi(0, "vimSep", { link = "GruvboxFg3" })
hi(0, "vimSet", { link = "Normal" })
hi(0, "vimSetSep", { link = "GruvboxFg3" })
hi(0, "vimUserFunc", { link = "Variable" })
hi(0, "vimUsrCmd", { link = "Macro" })
hi(0, "vimVar", { link = "Variable" })
hi(0, "xmlAttrib", { link = "Field" })
hi(0, "xmlAttribPunct", { link = "Punctuation" })
hi(0, "xmlCdata", { link = "String" })
hi(0, "xmlCdataCdata", { link = "Special" })
hi(0, "xmlCdataEnd", { link = "Punctuation" })
hi(0, "xmlCdataStart", { link = "Punctuation" })
hi(0, "xmlDocType", { link = "Field" })
hi(0, "xmlDocTypeDecl", { link = "Punctuation" })
hi(0, "xmlDocTypeKeyword", { link = "Special" })
hi(0, "xmlEndTag", { link = "Punctuation" })
hi(0, "xmlEntity", { link = "Special" })
hi(0, "xmlEntityPunct", { link = "Special" })
hi(0, "xmlEqual", { link = "Operator" })
hi(0, "xmlProcessingDelim", { link = "Punctuation" })
hi(0, "xmlTag", { link = "Punctuation" })
hi(0, "xmlTagName", { link = "Tag" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#282828"
g.terminal_color_1 = "#cc241d"
g.terminal_color_2 = "#98971a"
g.terminal_color_3 = "#d79921"
g.terminal_color_4 = "#458588"
g.terminal_color_5 = "#b16286"
g.terminal_color_6 = "#689d6a"
g.terminal_color_7 = "#a89984"
g.terminal_color_8 = "#928374"
g.terminal_color_9 = "#fb4934"
g.terminal_color_10 = "#b8bb26"
g.terminal_color_11 = "#fabd2f"
g.terminal_color_12 = "#83a598"
g.terminal_color_13 = "#d3869b"
g.terminal_color_14 = "#8ec07c"
g.terminal_color_15 = "#ebdbb2"
